main: de.raidcraft.skills.SkillsPlugin
name: Skills
version: ${project.version}#${build.number}
description: API for creating and using custom skills.
author: Silthus
website: http://www.raid-craft.de
depend: [RaidCraft-API]