name: Skills
version: 1.0-SNAPSHOT
description: API for creating and using custom skills.
author: Silthus
website: http://www.raid-craft.de

main: de.raidcraft.skills.SkillsPluginpend: [RaidCraft-API]